#!/bin/bash

# -------------------- umask
umask 022

# -------------------- add PATH to sudo
alias sudo='sudo env PATH=$PATH '

# -------------------- ls alias
alias l='ls'
alias ll='ls -lh'
alias la='ls -a'
alias lla='ls -lha'

# -------------------- export PATH
oldifs="$IFS"
IFS="
"
for dir in $(find "$HOME/local/" -type d -name "bin")
do
    absolute=$(readlink -e "$dir")
    if [[ "$absolute" ]]
    then
        export PATH="$PATH:$absolute"
    fi
done
IFS="$oldifs"
